name: Release a new version
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
jobs:
  init:
    name: Release a new version
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Node js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - name: Build files
        run: npx parcel build index.js -o granola.$(node -e "(function () { console.log(require('./package.json').version.split('.').join('-')) })()").js
      - name: Move configuration files
        run: cp -r events dist
      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'dist'      # optional: defaults to entire repository
